
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 13;
  public static final int LPAR = 2;
  public static final int STRING_LITERAL = 15;
  public static final int PLUS = 12;
  public static final int PREFIX = 8;
  public static final int EOF = 0;
  public static final int IF = 10;
  public static final int RBRACKET = 5;
  public static final int ELSE = 11;
  public static final int error = 1;
  public static final int COMMA = 6;
  public static final int SEMICOLON = 7;
  public static final int IDENTIFIER = 16;
  public static final int TIMES = 14;
  public static final int RPAR = 3;
  public static final int SUFFIX = 9;
  public static final int LBRACKET = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAR",
  "RPAR",
  "LBRACKET",
  "RBRACKET",
  "COMMA",
  "SEMICOLON",
  "PREFIX",
  "SUFFIX",
  "IF",
  "ELSE",
  "PLUS",
  "MINUS",
  "TIMES",
  "STRING_LITERAL",
  "IDENTIFIER"
  };
}

